language: node_js
node_js:
  - 'node'
  - 'lts/*'
sudo: required
script: echo "Skipping tests for now..."
before_deploy: 
  - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
  - chmod -R u+x ./Bluemix_CLI/bin
  - chmod +x ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: Project-Owl/ducks-to-db
    branch: master
  skip_cleanup: true

